spring:
  application:
    name: DormRepairSystem
  datasource:
    url: jdbc:mysql://localhost:3306/dorm_repair_system?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8082

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: org.example.dormrepairsystem.entity
  configuration:
    map-underscore-to-camel-case: true